### Importing Liberaries

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

### description of data

### Loading data

In [123]:
data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]

In [124]:
data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [125]:
target

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [126]:
df=pd.DataFrame(data,columns=['CRIM','ZN','INDUS','CHAS','NOX','RM','AGE','DIS','RAD','TAX','PTRATIO','B','LSTAT'])
df.shape

(506, 13)

In [127]:
df['MEDV']=target
df.shape

(506, 14)

### spliting the data

In [189]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=20)
#x_train.shape,x_test.shape
y.values.reshape(1,-1)


array([[24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
        19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
        20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
        23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
        33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
        21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
        20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
        23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
        15.6, 11.8, 13.8, 15.6, 14.6, 

In [190]:
y_train

7      27.1
268    43.5
80     28.0
30     12.7
450    13.4
       ... 
412    17.9
223    30.1
271    25.2
474    13.8
355    20.6
Name: MEDV, Length: 404, dtype: float64

### Random Forest Regressor

In [191]:
rf1=RandomForestRegressor(n_estimators=100)
rf1.fit(x_train,y_train)

RandomForestRegressor()

In [192]:
y_pred=rf1.predict(x_test)

In [193]:
from sklearn.metrics import mean_squared_error
error=mean_squared_error(y_test,y_pred)
error

14.140519490196068

## <font color='green'>K-Fold CrossValidation </font>

In [194]:
from sklearn.model_selection import KFold
kfold=KFold(n_splits=5,shuffle=False)

In [195]:
list(kfold.split(x))[0][1].shape

(102,)

In [196]:
list(kfold.split(x,y))[0]

(array([102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114,
        115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127,
        128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
        141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153,
        154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166,
        167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179,
        180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192,
        193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205,
        206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218,
        219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231,
        232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244,
        245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257,
        258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270,
        271, 272, 273, 274, 275, 276, 277, 278, 279

In [197]:
xtrain,xtest=list(kfold.split(x,y))[0][0],list(kfold.split(x,y))[0][1]
rf1.fit(x_train,y_train)

RandomForestRegressor()

In [198]:
len(list(kfold.split(x,y))[0])

2

In [199]:
for train_split,test_split in list(kfold.split(x)):
    print('Training set : \n',train_split)
    print("Testing set : \n",test_split)
    print('='*100,"\n")

Training set : 
 [102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155
 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173
 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191
 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209
 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227
 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245
 246 247 248 249 250 251 252 253 254 255 256 257 258 259 260 261 262 263
 264 265 266 267 268 269 270 271 272 273 274 275 276 277 278 279 280 281
 282 283 284 285 286 287 288 289 290 291 292 293 294 295 296 297 298 299
 300 301 302 303 304 305 306 307 308 309 310 311 312 313 314 315 316 317
 318 319 320 321 322 323 324 325 326 327 328 329 330 331 332 333 334 335
 336 337 338 339 340 341 342 343 3

##### now on these sets we have perform Random Forest Regressor

In [231]:
errors=[]
n_est=[100,200,300]
for i in n_est:
    print(f'errors in n_est_{i} : \n')
    j=1
    for train_index,test_index in list(kfold.split(x,y)):
        x_train,x_test=x[train_index],x[test_index]
        y_train,y_test=y[train_index],y[test_index]
        
        rf1=RandomForestRegressor(n_estimators=i)
        rf1=rf1.fit(x_train,y_train)
        y_pred=rf1.predict(x_test)
        error=mean_squared_error(y_test,y_pred)
        errors.append(error)
    
        print(f'fold no {j} : ',error)
        j+=1
    
    avg_error=np.average(np.array(errors))
        
    print(f'average error : ',avg_error)    
    print('='*30)   
        


errors in n_est_100 : 

fold no 1 :  8.484167382352929
fold no 2 :  13.138039405940617
fold no 3 :  23.127113742574235
fold no 4 :  46.46441853465346
fold no 5 :  21.669732118811865
average error :  22.576694236866622
errors in n_est_200 : 

fold no 1 :  7.871012404411763
fold no 2 :  13.421980967821812
fold no 3 :  21.185040742574255
fold no 4 :  46.45910375742575
fold no 5 :  18.77970481435646
average error :  22.060031387092316
errors in n_est_300 : 

fold no 1 :  8.106858079520714
fold no 2 :  13.420874085808576
fold no 3 :  21.22339004180424
fold no 4 :  46.50965335423552
fold no 5 :  18.161612649064935
average error :  21.868180138757143


In [229]:
print(errors)

len(errors)

[7.892161813725481, 13.135354069306953, 21.004155346534628, 46.55028562376234, 19.28556699009899, 8.131023517156871, 12.905585502475283, 20.32185530693069, 46.82530410148516, 20.291418715346545, 8.096439754901978, 13.238655096809666, 20.807456188118877, 45.32008654345439, 19.459889553355357]


15

In [232]:
#avg of 15 error
avg_error=np.average(np.array(errors))
avg_error

21.868180138757143